# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f3a4bf2bd892350d26dec31de6fd3da7d1f9affd352b1a578e66e706201a4a6cc2e5b0ecc9a4404d13b06e21e6bc6e33fbbba0dd633646dce6d143020751846

test:
  secret_key_base: 6df1ba81b923305f9f947cc82335f8a1537f529461af84c7d638050d0239f1211763a2140c07294dd72de2c7abb0eca18680081b0aa7ad24d0e74a1a20067651

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
